apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydemoapp
  template:
    metadata:
      labels:
        app: mydemoapp
    spec:
      containers:
      - name: mydemoapp
        image: mydemoapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mydemoapp-service
spec:
  type: NodePort
  selector:
    app: mydemoapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
